"""Initial Migration

Revision ID: 618249a904c6
Revises: d23fba2bc977
Create Date: 2019-10-01 10:19:12.244329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618249a904c6'
down_revision = 'd23fba2bc977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('productId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'products', ['productId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'productId')
    # ### end Alembic commands ###
